
import type { Metadata } from "next";
import localfont from "next/font/local";

import { Epilogue, Sora } from "next/font/google";

import "./globals.css";
import "../../public/css/style.css";
import Script from "next/script";

const epilogue = Epilogue({
  variable: "--font-epilogue",
  subsets: ["latin"],
});

const sora = Sora({
  variable: "--font-sora",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
          integrity="sha512-papapapapapapap..." 
          crossOrigin="anonymous"
          referrerPolicy="no-referrer"
        />
      </head>
      <body
        className={`antialiased ${epilogue.variable} ${sora.variable}`}
      >
        {children}
      </body>
      <Script
        src="/js/script.js"
        strategy="afterInteractive" 
      />
    </html>
  );
}
